spring:
  application:
    name: yue-lao-demo
  datasource:
    url: jdbc:mysql://localhost:3306/yuelao?useSSL=false&useUnicode=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari: # https://github.com/brettwooldridge/HikariCP (uses milliseconds for all time values)
      maximum-pool-size: 20 # 连接池最大连接数，默认是10
      minimum-idle: 5 # 最小空闲连接数量
      idle-timeout: 600000 # 空闲连接存活最大时间，默认600000（10分钟）
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
      max-lifetime: 180000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
server:
  port: 2998
  servlet:
    context-path: /yuelao
logging:
  config: classpath:logback-dev.xml
